"""The Ghidra adapter protocol + its plain-model vocabulary.

All data models come from platform.models (importable by every layer);
this module holds the *interface* and nothing else. ghidra/ and fake/
implement it, services/ consume it, and a contract test asserts method-set
parity between the real and fake implementations.
"""

from __future__ import annotations

from typing import Protocol, runtime_checkable

from ghmcp.platform.models import (  # noqa: F401  # re-exported for convenience
    CallGraphPage,
    CallGraphRequest,
    CommentRequest,
    DecompiledFn,
    DecompileRequest,
    DiffRequest,
    EnvInfo,
    FunctionBrief,
    Hit,
    Insn,
    InstructionsRequest,
    Model,
    OpenSpec,
    ProgramInfo,
    PrototypeRequest,
    ReadRequest,
    Ref,
    RefsRequest,
    RenameRequest,
    SearchQuery,
    StringEntry,
    StringQuery,
    Symbol,
    SymbolQuery,
)


@runtime_checkable
class GhidraAdapter(Protocol):
    """All Ghidra touchpoints. Implemented by ghidra/backend.py (real) and fake/ (CI).

    Every method is synchronous and thread-safe to call from the JVM worker
    pool; write methods are wrapped in a transaction by the real backend.
    """

    # --- lifecycle ----------------------------------------------------------
    def open(self, spec: OpenSpec) -> ProgramInfo: ...
    def close(self, pid: str) -> None: ...
    def save(self, pid: str) -> None: ...
    def list_open(self) -> list[ProgramInfo]: ...
    def modification_number(self, pid: str) -> int: ...
    def env(self) -> EnvInfo: ...
    def select(self, pid: str) -> None: ...
    def current(self) -> str | None: ...
    def shutdown(self) -> None: ...  # teardown native resources (decompiler pool)

    # --- read ---------------------------------------------------------------
    def decompile(self, pid: str, request: DecompileRequest) -> list[DecompiledFn]: ...
    def instructions(self, pid: str, request: InstructionsRequest) -> list[Insn]: ...
    def refs(self, pid: str, request: RefsRequest) -> tuple[list[Ref], bool]: ...  # (rows, more)
    def symbols(self, pid: str, request: SymbolQuery) -> tuple[list[Symbol], bool]: ...
    def strings(self, pid: str, request: StringQuery) -> tuple[list[StringEntry], bool]: ...
    def call_graph(self, pid: str, request: CallGraphRequest) -> CallGraphPage: ...
    def read(self, pid: str, address: int, length: int) -> bytes: ...
    def find(self, pid: str, request: SearchQuery) -> list[Hit]: ...

    # --- write (transaction-guarded in the real backend) ----------------------
    def rename(self, pid: str, request: RenameRequest) -> None: ...
    def set_prototype(self, pid: str, request: PrototypeRequest) -> None: ...
    def set_comment(self, pid: str, request: CommentRequest) -> None: ...
    def define_types(self, pid: str, c_decl: str) -> list[str]: ...
    def apply_type(self, pid: str, address: int, c_type: str, variable: str | None) -> None: ...
    def list_types(self, pid: str) -> list[str]: ...
    def get_type(self, pid: str, name: str) -> dict: ...

    # --- game specials ----------------------------------------------------------
    def memory_map(self, pid: str) -> list[dict]: ...
    def create_block(self, pid: str, name: str, address: int, size: int, flags: str) -> None: ...
    def rebase(self, pid: str, new_base: int) -> None: ...
    def diff_functions(self, a_pid: str, b_pid: str) -> dict: ...
    def diff_bytes(self, a_pid: str, b_pid: str, start: int, end: int) -> dict: ...
    def analysis_state(self, pid: str) -> str: ...
    def run_analysis(self, pid: str, options: dict) -> None: ...
    def analysis_options(self, pid: str) -> dict: ...

    # --- scripts/escape hatch ---------------------------------------------------
    def run_script(
        self, pid: str | None, kind: str, code: str | None, path: str | None, args: list[str]
    ) -> dict: ...

    # --- tasks (analysis) -------------------------------------------------------
    def analyze_async(self, pid: str, options: dict | None) -> str: ...
    def task_status(self, task_id: str) -> dict: ...
